hw-3
gab1k/ml_base pull request #3
Opened 2024-03-15 18:43 UTC by gab1k

2024-03-16 13:14 UTC, svkov requested changes
Поправь замечание. Пока 0.4

2024-03-16 13:14 UTC, svkov commented on notebooks/03-homework.ipynb
> +      "Хуже всего распознаются знаки:  Bicycles crossing\n"
Задача в том, чтобы понять какие два класса путает модель, а не посмотреть худшую метрику для класса. Объяснял на лекции подробнее, запись есть.

2024-03-22 22:09 UTC, gab1k commented on notebooks/03-homework.ipynb
> +      "Хуже всего распознаются знаки:  Bicycles crossing\n"
поправил

2024-03-23 12:43 UTC, svkov approved these changes
Зачтено

2024-03-23 14:44 UTC, merged